const Images = {
  BackBtn: require("../../assets/icons/backArrow.png"),
  NoResults: require("../../assets/icons/NoResults.png"),
  // Splash: require("../../assets/images/TestUser.png"),
  // OverlayPhone: require("../../assets/icons/DisposalWater.png"),
  logo: require("./../../assets/images/logo.png"),
  printer: require("./../../assets/images/printer.png"),
  buySupplies: require("./../../assets/icons/buy_supplies.png"),
  buyPrinters: require("./../../assets/icons/buy_printer.png"),
  instructions: require("./../../assets/icons/instructions.png"),
  helpAndSupport: require("./../../assets/icons/help_and_support.png"),
  aboutCognitive: require("./../../assets/icons/about_cognitive.png"),
  addPrinterToComputer: require("./../../assets/icons/add_printer_to_computer.png"),
  printer2: require("./../../assets/images/printer2.png"),
  power: require("./../../assets/icons/power.png"),
  bluetooth: require("./../../assets/icons/bluetooth.png"),
  printerFilled: require("./../../assets/icons/printer-filled.png"),
  wifi: require("./../../assets/icons/wifi.png"),
  printerOutline: require("./../../assets/images/printer-outline.png"),
  printerOutlineWithoutBg: require("./../../assets/images/printer-outline-without-bg.png"),
  rightArrow: require("./../../assets/icons/rightArrow.png"),
  printerWithCheck: require("./../../assets/images/printer-with-check.png"),
  verticalDots: require("./../../assets/icons/verticalDots.png"),
  bin: require("./../../assets/icons/bin.png"),
  plusIcon: require("./../../assets/icons/plus-icon.png"),
  wifiRound: require("./../../assets/icons/wifi-round.png"),
  refresh: require("./../../assets/icons/refresh.png"),
  networkInformation: require("./../../assets/icons/networkInformation.png"),
  printerSettingIcon: require("./../../assets/icons/printerSettingIcon.png"),
  mediaSetting: require("./../../assets/icons/mediaSetting.png"),
  advanceSetting: require("./../../assets/icons/advanceSetting.png"),
  openHttpsServer: require("./../../assets/icons/openHttpServer.png"),
  startCalibration: require("./../../assets/icons/startCalibration.png"),
  printDiagnosticLabel: require("./../../assets/icons/printDiagnosticLabel.png"),
  printTestLabel: require("./../../assets/icons/printTestLab.png"),
  factoryReset: require("./../../assets/icons/factoryReset.png"),
  minus: require("./../../assets/icons/minus.png"),
  plus: require("./../../assets/icons/plus.png"),
  eye: require("./../../assets/icons/eye.png"),
  eyeClose: require("./../../assets/icons/eye-close.png"),
  successPrinter: require("./../../assets/icons/success-printer.png"),
  failPrinter: require("./../../assets/icons/printer-red.png"),
  tickGreen: require("./../../assets/icons/tick-green.png"),
  phone: require("./../../assets/icons/phone.png"),
  crossRed: require("./../../assets/icons/cross-red.png"),
  printerWithCross: require("./../../assets/icons/printerWithCross.png"),
  printerWithClip: require("./../../assets/icons/printerWithClip.png"),
  successPrinter2: require("./../../assets/icons/printerSuccess2.png"),
  failBluetooth: require("./../../assets/icons/failBluetooth.png"),
  failWifi: require("./../../assets/icons/failWifi.png"),
  genralError: require("./../../assets/icons/genralError.png"),

  Home: require("./../../assets/icons/home.png"),
  Cart: require("./../../assets/icons/cart.png"),
  Orders: require("./../../assets/icons/orders.png"),
  Profile: require("./../../assets/icons/profile.png"),
  Search: require("./../../assets/icons/search.png"),
  filter: require("./../../assets/icons/filter.png"),
  arrowDown: require("./../../assets/icons/arrowDown.png"),
  heart: require("./../../assets/icons/heart.png"),
};

export default Images;
