// source: common.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.AuthMode', null, global);
goog.exportSymbol('proto.Band', null, global);
goog.exportSymbol('proto.ConnectionFailureReason', null, global);
goog.exportSymbol('proto.ConnectionState', null, global);
goog.exportSymbol('proto.OpCode', null, global);
goog.exportSymbol('proto.ScanParams', null, global);
goog.exportSymbol('proto.Status', null, global);
goog.exportSymbol('proto.WifiInfo', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ScanParams = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ScanParams, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ScanParams.displayName = 'proto.ScanParams';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.WifiInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.WifiInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.WifiInfo.displayName = 'proto.WifiInfo';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ScanParams.prototype.toObject = function(opt_includeInstance) {
  return proto.ScanParams.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ScanParams} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ScanParams.toObject = function(includeInstance, msg) {
  var f, obj = {
    band: jspb.Message.getFieldWithDefault(msg, 1, 0),
    passive: jspb.Message.getBooleanFieldWithDefault(msg, 2, false),
    periodMs: jspb.Message.getFieldWithDefault(msg, 3, 0),
    groupChannels: (f = jspb.Message.getField(msg, 4)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ScanParams}
 */
proto.ScanParams.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ScanParams;
  return proto.ScanParams.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ScanParams} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ScanParams}
 */
proto.ScanParams.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.Band} */ (reader.readEnum());
      msg.setBand(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setPassive(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setPeriodMs(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setGroupChannels(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ScanParams.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ScanParams.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ScanParams} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ScanParams.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {!proto.Band} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = /** @type {boolean} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeBool(
      2,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeUint32(
      3,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeUint32(
      4,
      f
    );
  }
};


/**
 * optional Band band = 1;
 * @return {!proto.Band}
 */
proto.ScanParams.prototype.getBand = function() {
  return /** @type {!proto.Band} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.Band} value
 * @return {!proto.ScanParams} returns this
 */
proto.ScanParams.prototype.setBand = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.ScanParams} returns this
 */
proto.ScanParams.prototype.clearBand = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ScanParams.prototype.hasBand = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional bool passive = 2;
 * @return {boolean}
 */
proto.ScanParams.prototype.getPassive = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.ScanParams} returns this
 */
proto.ScanParams.prototype.setPassive = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.ScanParams} returns this
 */
proto.ScanParams.prototype.clearPassive = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ScanParams.prototype.hasPassive = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional uint32 period_ms = 3;
 * @return {number}
 */
proto.ScanParams.prototype.getPeriodMs = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.ScanParams} returns this
 */
proto.ScanParams.prototype.setPeriodMs = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.ScanParams} returns this
 */
proto.ScanParams.prototype.clearPeriodMs = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ScanParams.prototype.hasPeriodMs = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional uint32 group_channels = 4;
 * @return {number}
 */
proto.ScanParams.prototype.getGroupChannels = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.ScanParams} returns this
 */
proto.ScanParams.prototype.setGroupChannels = function(value) {
  return jspb.Message.setField(this, 4, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.ScanParams} returns this
 */
proto.ScanParams.prototype.clearGroupChannels = function() {
  return jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ScanParams.prototype.hasGroupChannels = function() {
  return jspb.Message.getField(this, 4) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.WifiInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.WifiInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.WifiInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.WifiInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    ssid: msg.getSsid_asB64(),
    bssid: msg.getBssid_asB64(),
    band: (f = jspb.Message.getField(msg, 3)) == null ? undefined : f,
    channel: (f = jspb.Message.getField(msg, 4)) == null ? undefined : f,
    auth: (f = jspb.Message.getField(msg, 5)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.WifiInfo}
 */
proto.WifiInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.WifiInfo;
  return proto.WifiInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.WifiInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.WifiInfo}
 */
proto.WifiInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setSsid(value);
      break;
    case 2:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setBssid(value);
      break;
    case 3:
      var value = /** @type {!proto.Band} */ (reader.readEnum());
      msg.setBand(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readUint32());
      msg.setChannel(value);
      break;
    case 5:
      var value = /** @type {!proto.AuthMode} */ (reader.readEnum());
      msg.setAuth(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.WifiInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.WifiInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.WifiInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.WifiInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {!(string|Uint8Array)} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeBytes(
      1,
      f
    );
  }
  f = /** @type {!(string|Uint8Array)} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeBytes(
      2,
      f
    );
  }
  f = /** @type {!proto.Band} */ (jspb.Message.getField(message, 3));
  if (f != null) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = /** @type {number} */ (jspb.Message.getField(message, 4));
  if (f != null) {
    writer.writeUint32(
      4,
      f
    );
  }
  f = /** @type {!proto.AuthMode} */ (jspb.Message.getField(message, 5));
  if (f != null) {
    writer.writeEnum(
      5,
      f
    );
  }
};


/**
 * required bytes ssid = 1;
 * @return {!(string|Uint8Array)}
 */
proto.WifiInfo.prototype.getSsid = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * required bytes ssid = 1;
 * This is a type-conversion wrapper around `getSsid()`
 * @return {string}
 */
proto.WifiInfo.prototype.getSsid_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getSsid()));
};


/**
 * required bytes ssid = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getSsid()`
 * @return {!Uint8Array}
 */
proto.WifiInfo.prototype.getSsid_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getSsid()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.WifiInfo} returns this
 */
proto.WifiInfo.prototype.setSsid = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.WifiInfo} returns this
 */
proto.WifiInfo.prototype.clearSsid = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.WifiInfo.prototype.hasSsid = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * required bytes bssid = 2;
 * @return {!(string|Uint8Array)}
 */
proto.WifiInfo.prototype.getBssid = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * required bytes bssid = 2;
 * This is a type-conversion wrapper around `getBssid()`
 * @return {string}
 */
proto.WifiInfo.prototype.getBssid_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getBssid()));
};


/**
 * required bytes bssid = 2;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getBssid()`
 * @return {!Uint8Array}
 */
proto.WifiInfo.prototype.getBssid_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getBssid()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.WifiInfo} returns this
 */
proto.WifiInfo.prototype.setBssid = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.WifiInfo} returns this
 */
proto.WifiInfo.prototype.clearBssid = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.WifiInfo.prototype.hasBssid = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional Band band = 3;
 * @return {!proto.Band}
 */
proto.WifiInfo.prototype.getBand = function() {
  return /** @type {!proto.Band} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.Band} value
 * @return {!proto.WifiInfo} returns this
 */
proto.WifiInfo.prototype.setBand = function(value) {
  return jspb.Message.setField(this, 3, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.WifiInfo} returns this
 */
proto.WifiInfo.prototype.clearBand = function() {
  return jspb.Message.setField(this, 3, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.WifiInfo.prototype.hasBand = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * required uint32 channel = 4;
 * @return {number}
 */
proto.WifiInfo.prototype.getChannel = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {number} value
 * @return {!proto.WifiInfo} returns this
 */
proto.WifiInfo.prototype.setChannel = function(value) {
  return jspb.Message.setField(this, 4, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.WifiInfo} returns this
 */
proto.WifiInfo.prototype.clearChannel = function() {
  return jspb.Message.setField(this, 4, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.WifiInfo.prototype.hasChannel = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional AuthMode auth = 5;
 * @return {!proto.AuthMode}
 */
proto.WifiInfo.prototype.getAuth = function() {
  return /** @type {!proto.AuthMode} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {!proto.AuthMode} value
 * @return {!proto.WifiInfo} returns this
 */
proto.WifiInfo.prototype.setAuth = function(value) {
  return jspb.Message.setField(this, 5, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.WifiInfo} returns this
 */
proto.WifiInfo.prototype.clearAuth = function() {
  return jspb.Message.setField(this, 5, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.WifiInfo.prototype.hasAuth = function() {
  return jspb.Message.getField(this, 5) != null;
};


/**
 * @enum {number}
 */
proto.OpCode = {
  RESERVED: 0,
  GET_STATUS: 1,
  START_SCAN: 2,
  STOP_SCAN: 3,
  SET_CONFIG: 4,
  FORGET_CONFIG: 5
};

/**
 * @enum {number}
 */
proto.Status = {
  SUCCESS: 0,
  INVALID_ARGUMENT: 1,
  INVALID_PROTO: 2,
  INTERNAL_ERROR: 3
};

/**
 * @enum {number}
 */
proto.ConnectionState = {
  DISCONNECTED: 0,
  AUTHENTICATION: 1,
  ASSOCIATION: 2,
  OBTAINING_IP: 3,
  CONNECTED: 4,
  CONNECTION_FAILED: 5
};

/**
 * @enum {number}
 */
proto.ConnectionFailureReason = {
  AUTH_ERROR: 0,
  NETWORK_NOT_FOUND: 1,
  TIMEOUT: 2,
  FAIL_IP: 3,
  FAIL_CONN: 4
};

/**
 * @enum {number}
 */
proto.Band = {
  BAND_ANY: 0,
  BAND_2_4_GH: 1,
  BAND_5_GH: 2
};

/**
 * @enum {number}
 */
proto.AuthMode = {
  OPEN: 0,
  WEP: 1,
  WPA_PSK: 2,
  WPA2_PSK: 3,
  WPA_WPA2_PSK: 4,
  WPA2_ENTERPRISE: 5,
  WPA3_PSK: 6
};

goog.object.extend(exports, proto);
