// source: response.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var common_pb = require('./common_pb.js');
goog.object.extend(proto, common_pb);
goog.exportSymbol('proto.ConnectionInfo', null, global);
goog.exportSymbol('proto.DeviceStatus', null, global);
goog.exportSymbol('proto.Response', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.ConnectionInfo = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.ConnectionInfo, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.ConnectionInfo.displayName = 'proto.ConnectionInfo';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.DeviceStatus = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.DeviceStatus, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.DeviceStatus.displayName = 'proto.DeviceStatus';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Response = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Response, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Response.displayName = 'proto.Response';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.ConnectionInfo.prototype.toObject = function(opt_includeInstance) {
  return proto.ConnectionInfo.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.ConnectionInfo} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ConnectionInfo.toObject = function(includeInstance, msg) {
  var f, obj = {
    ip4Addr: msg.getIp4Addr_asB64()
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.ConnectionInfo}
 */
proto.ConnectionInfo.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.ConnectionInfo;
  return proto.ConnectionInfo.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.ConnectionInfo} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.ConnectionInfo}
 */
proto.ConnectionInfo.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!Uint8Array} */ (reader.readBytes());
      msg.setIp4Addr(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.ConnectionInfo.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.ConnectionInfo.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.ConnectionInfo} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.ConnectionInfo.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {!(string|Uint8Array)} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeBytes(
      1,
      f
    );
  }
};


/**
 * optional bytes ip4_addr = 1;
 * @return {!(string|Uint8Array)}
 */
proto.ConnectionInfo.prototype.getIp4Addr = function() {
  return /** @type {!(string|Uint8Array)} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * optional bytes ip4_addr = 1;
 * This is a type-conversion wrapper around `getIp4Addr()`
 * @return {string}
 */
proto.ConnectionInfo.prototype.getIp4Addr_asB64 = function() {
  return /** @type {string} */ (jspb.Message.bytesAsB64(
      this.getIp4Addr()));
};


/**
 * optional bytes ip4_addr = 1;
 * Note that Uint8Array is not supported on all browsers.
 * @see http://caniuse.com/Uint8Array
 * This is a type-conversion wrapper around `getIp4Addr()`
 * @return {!Uint8Array}
 */
proto.ConnectionInfo.prototype.getIp4Addr_asU8 = function() {
  return /** @type {!Uint8Array} */ (jspb.Message.bytesAsU8(
      this.getIp4Addr()));
};


/**
 * @param {!(string|Uint8Array)} value
 * @return {!proto.ConnectionInfo} returns this
 */
proto.ConnectionInfo.prototype.setIp4Addr = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.ConnectionInfo} returns this
 */
proto.ConnectionInfo.prototype.clearIp4Addr = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.ConnectionInfo.prototype.hasIp4Addr = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.DeviceStatus.prototype.toObject = function(opt_includeInstance) {
  return proto.DeviceStatus.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.DeviceStatus} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.DeviceStatus.toObject = function(includeInstance, msg) {
  var f, obj = {
    state: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    provisioningInfo: (f = msg.getProvisioningInfo()) && common_pb.WifiInfo.toObject(includeInstance, f),
    connectionInfo: (f = msg.getConnectionInfo()) && proto.ConnectionInfo.toObject(includeInstance, f),
    scanInfo: (f = msg.getScanInfo()) && common_pb.ScanParams.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.DeviceStatus}
 */
proto.DeviceStatus.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.DeviceStatus;
  return proto.DeviceStatus.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.DeviceStatus} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.DeviceStatus}
 */
proto.DeviceStatus.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.ConnectionState} */ (reader.readEnum());
      msg.setState(value);
      break;
    case 10:
      var value = new common_pb.WifiInfo;
      reader.readMessage(value,common_pb.WifiInfo.deserializeBinaryFromReader);
      msg.setProvisioningInfo(value);
      break;
    case 11:
      var value = new proto.ConnectionInfo;
      reader.readMessage(value,proto.ConnectionInfo.deserializeBinaryFromReader);
      msg.setConnectionInfo(value);
      break;
    case 12:
      var value = new common_pb.ScanParams;
      reader.readMessage(value,common_pb.ScanParams.deserializeBinaryFromReader);
      msg.setScanInfo(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.DeviceStatus.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.DeviceStatus.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.DeviceStatus} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.DeviceStatus.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {!proto.ConnectionState} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getProvisioningInfo();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      common_pb.WifiInfo.serializeBinaryToWriter
    );
  }
  f = message.getConnectionInfo();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      proto.ConnectionInfo.serializeBinaryToWriter
    );
  }
  f = message.getScanInfo();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      common_pb.ScanParams.serializeBinaryToWriter
    );
  }
};


/**
 * optional ConnectionState state = 1;
 * @return {!proto.ConnectionState}
 */
proto.DeviceStatus.prototype.getState = function() {
  return /** @type {!proto.ConnectionState} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.ConnectionState} value
 * @return {!proto.DeviceStatus} returns this
 */
proto.DeviceStatus.prototype.setState = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.DeviceStatus} returns this
 */
proto.DeviceStatus.prototype.clearState = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.DeviceStatus.prototype.hasState = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional WifiInfo provisioning_info = 10;
 * @return {?proto.WifiInfo}
 */
proto.DeviceStatus.prototype.getProvisioningInfo = function() {
  return /** @type{?proto.WifiInfo} */ (
    jspb.Message.getWrapperField(this, common_pb.WifiInfo, 10));
};


/**
 * @param {?proto.WifiInfo|undefined} value
 * @return {!proto.DeviceStatus} returns this
*/
proto.DeviceStatus.prototype.setProvisioningInfo = function(value) {
  return jspb.Message.setWrapperField(this, 10, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.DeviceStatus} returns this
 */
proto.DeviceStatus.prototype.clearProvisioningInfo = function() {
  return this.setProvisioningInfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.DeviceStatus.prototype.hasProvisioningInfo = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional ConnectionInfo connection_info = 11;
 * @return {?proto.ConnectionInfo}
 */
proto.DeviceStatus.prototype.getConnectionInfo = function() {
  return /** @type{?proto.ConnectionInfo} */ (
    jspb.Message.getWrapperField(this, proto.ConnectionInfo, 11));
};


/**
 * @param {?proto.ConnectionInfo|undefined} value
 * @return {!proto.DeviceStatus} returns this
*/
proto.DeviceStatus.prototype.setConnectionInfo = function(value) {
  return jspb.Message.setWrapperField(this, 11, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.DeviceStatus} returns this
 */
proto.DeviceStatus.prototype.clearConnectionInfo = function() {
  return this.setConnectionInfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.DeviceStatus.prototype.hasConnectionInfo = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional ScanParams scan_info = 12;
 * @return {?proto.ScanParams}
 */
proto.DeviceStatus.prototype.getScanInfo = function() {
  return /** @type{?proto.ScanParams} */ (
    jspb.Message.getWrapperField(this, common_pb.ScanParams, 12));
};


/**
 * @param {?proto.ScanParams|undefined} value
 * @return {!proto.DeviceStatus} returns this
*/
proto.DeviceStatus.prototype.setScanInfo = function(value) {
  return jspb.Message.setWrapperField(this, 12, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.DeviceStatus} returns this
 */
proto.DeviceStatus.prototype.clearScanInfo = function() {
  return this.setScanInfo(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.DeviceStatus.prototype.hasScanInfo = function() {
  return jspb.Message.getField(this, 12) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Response.prototype.toObject = function(opt_includeInstance) {
  return proto.Response.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Response} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Response.toObject = function(includeInstance, msg) {
  var f, obj = {
    requestOpCode: (f = jspb.Message.getField(msg, 1)) == null ? undefined : f,
    status: (f = jspb.Message.getField(msg, 2)) == null ? undefined : f,
    deviceStatus: (f = msg.getDeviceStatus()) && proto.DeviceStatus.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Response}
 */
proto.Response.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Response;
  return proto.Response.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Response} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Response}
 */
proto.Response.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.OpCode} */ (reader.readEnum());
      msg.setRequestOpCode(value);
      break;
    case 2:
      var value = /** @type {!proto.Status} */ (reader.readEnum());
      msg.setStatus(value);
      break;
    case 10:
      var value = new proto.DeviceStatus;
      reader.readMessage(value,proto.DeviceStatus.deserializeBinaryFromReader);
      msg.setDeviceStatus(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Response.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Response.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Response} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Response.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = /** @type {!proto.OpCode} */ (jspb.Message.getField(message, 1));
  if (f != null) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = /** @type {!proto.Status} */ (jspb.Message.getField(message, 2));
  if (f != null) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getDeviceStatus();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      proto.DeviceStatus.serializeBinaryToWriter
    );
  }
};


/**
 * optional OpCode request_op_code = 1;
 * @return {!proto.OpCode}
 */
proto.Response.prototype.getRequestOpCode = function() {
  return /** @type {!proto.OpCode} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.OpCode} value
 * @return {!proto.Response} returns this
 */
proto.Response.prototype.setRequestOpCode = function(value) {
  return jspb.Message.setField(this, 1, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Response} returns this
 */
proto.Response.prototype.clearRequestOpCode = function() {
  return jspb.Message.setField(this, 1, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Response.prototype.hasRequestOpCode = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional Status status = 2;
 * @return {!proto.Status}
 */
proto.Response.prototype.getStatus = function() {
  return /** @type {!proto.Status} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.Status} value
 * @return {!proto.Response} returns this
 */
proto.Response.prototype.setStatus = function(value) {
  return jspb.Message.setField(this, 2, value);
};


/**
 * Clears the field making it undefined.
 * @return {!proto.Response} returns this
 */
proto.Response.prototype.clearStatus = function() {
  return jspb.Message.setField(this, 2, undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Response.prototype.hasStatus = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional DeviceStatus device_status = 10;
 * @return {?proto.DeviceStatus}
 */
proto.Response.prototype.getDeviceStatus = function() {
  return /** @type{?proto.DeviceStatus} */ (
    jspb.Message.getWrapperField(this, proto.DeviceStatus, 10));
};


/**
 * @param {?proto.DeviceStatus|undefined} value
 * @return {!proto.Response} returns this
*/
proto.Response.prototype.setDeviceStatus = function(value) {
  return jspb.Message.setWrapperField(this, 10, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Response} returns this
 */
proto.Response.prototype.clearDeviceStatus = function() {
  return this.setDeviceStatus(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Response.prototype.hasDeviceStatus = function() {
  return jspb.Message.getField(this, 10) != null;
};


goog.object.extend(exports, proto);
